"""empty message

Revision ID: 867572a9dee4
Revises: 9daeb34ff849
Create Date: 2020-03-02 21:10:42.507449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867572a9dee4'
down_revision = '9daeb34ff849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
